### ISSUE TITLE
Finalizar primeira entrega

### ISSUE THREAD

**Issue by omadson** [carloap/dataviz-mapeamento-criminalidade#1]
Como combinado, a primeira entrega consistia em uma análise exploratória dos dados que escolheram. Para tal, vocês necessitam estar com o respositório organizado e ainda faltam algumas coisas. Ontem resolvemos alguns problemas, mas ainda faltam algumas coisas, a saber:

 - [x] Criar repositório
 - [x] Preencher README com as informações do projeto
 - [x] Atualizar o repositório com a análise exploratória
 - [x] Criar release no github com o título `Entrega 1` e a tag `v0.1.0`
 - [x] Clonar template do projeto
 - [x] Colocar conteúdo do repositório antigo no novo
 - [x] colocar @omadson como colaborador
 - [x] Melhorar conteúdo da análise exploratória (notebook)
 
A medida que forem concluindo estas tarefas, podem ir preenchendo os checkboxes. Qualquer dúvida, podem falar nessa issue.

**Comment by carloap** [comment]
# TODO
1) Normalizar e Classificar Dados por variáveis categóricas: fontes de 2015 a 2021
1-2) Classificar período usando modelo de distância, para series temporais.
1-3) Classificar idades (variável observável) e correlacionar e identificar as demais colunas (natureza, arma utilizada)

2) Dados socio-econômicos: enriquecer por municipio e período, os dados socio-econômicos - IBGE

3) Dados de escolaridade, saúde: enriquecer com dados de de saúde, hospitais e educação - IPECE

**Comment by omadson** [comment]
Quais as novidades, pessoal? Conseguiram fazer mais alguma coisa? o que falta pra finalizar?

**Comment by carloap** [comment]
Madson, atualizei a análise exploratória. Acredito estar um pouco mais rico em detalhes, mas vou ainda ver com o time para já aplicar dados externos

**Comment by omadson** [comment]
Ótimo, @carloap. Então pode criar a release e fechar essa issue. Aí partimos pros próximos passos.

**Comment by carloap** [comment]
Feito! v0.1.0 publicada

**Comment by omadson** [comment]
Ótimo, vou fechar aqui.
